package pacientes.entity;
// Generated 06-dic-2018 4:24:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private int idDomicilio;
     private Localidad localidad;
     private Provincia provincia;
     private String calle;
     private Integer numero;
     private Integer codpostal;
     private Integer piso;
     private Integer dpto;
     private Set pacientes = new HashSet(0);

    public Domicilio() {
    }

	
    public Domicilio(int idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
    public Domicilio(int idDomicilio, Localidad localidad, Provincia provincia, String calle, Integer numero, Integer codpostal, Integer piso, Integer dpto, Set pacientes) {
       this.idDomicilio = idDomicilio;
       this.localidad = localidad;
       this.provincia = provincia;
       this.calle = calle;
       this.numero = numero;
       this.codpostal = codpostal;
       this.piso = piso;
       this.dpto = dpto;
       this.pacientes = pacientes;
    }
   
    public int getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(int idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(Integer codpostal) {
        this.codpostal = codpostal;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public Integer getDpto() {
        return this.dpto;
    }
    
    public void setDpto(Integer dpto) {
        this.dpto = dpto;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }




}


