package pacientes.entity;
// Generated 30-nov-2018 19:32:04 by Hibernate Tools 4.3.1



/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private Integer idDomicilio;
     private Localidad localidad;
     private Paciente paciente;
     private Provincia provincia;
     private String calle;
     private Integer numero;
     private Integer codpostal;
     private Integer piso;
     private String dpto;

    public Domicilio() {
    }

    public Domicilio(Localidad localidad, Paciente paciente, Provincia provincia, String calle, Integer numero, Integer codpostal, Integer piso, String dpto) {
       this.localidad = localidad;
       this.paciente = paciente;
       this.provincia = provincia;
       this.calle = calle;
       this.numero = numero;
       this.codpostal = codpostal;
       this.piso = piso;
       this.dpto = dpto;
    }
   
    public Integer getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(Integer idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(Integer codpostal) {
        this.codpostal = codpostal;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public String getDpto() {
        return this.dpto;
    }
    
    public void setDpto(String dpto) {
        this.dpto = dpto;
    }




}


