package pacientes.entity;
// Generated 30-nov-2018 19:32:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int idlocalidad;
     private Provincia provincia;
     private String nombre;
     private Set domicilios = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(int idlocalidad) {
        this.idlocalidad = idlocalidad;
    }
    public Localidad(int idlocalidad, Provincia provincia, String nombre, Set domicilios) {
       this.idlocalidad = idlocalidad;
       this.provincia = provincia;
       this.nombre = nombre;
       this.domicilios = domicilios;
    }
   
    public int getIdlocalidad() {
        return this.idlocalidad;
    }
    
    public void setIdlocalidad(int idlocalidad) {
        this.idlocalidad = idlocalidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set domicilios) {
        this.domicilios = domicilios;
    }




}


