package pacientes.entity;
// Generated 06-dic-2018 4:24:06 by Hibernate Tools 4.3.1



/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer idpaciente;
     private Domicilio domicilio;
     private String nombre;
     private String apellido;
     private String tipodoc;
     private Integer nrodoc;
     private Integer telefono;
     private String email;

    public Paciente() {
    }

    public Paciente(Domicilio domicilio, String nombre, String apellido, String tipodoc, Integer nrodoc, Integer telefono, String email) {
       this.domicilio = domicilio;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipodoc = tipodoc;
       this.nrodoc = nrodoc;
       this.telefono = telefono;
       this.email = email;
    }
   
    public Integer getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(Integer idpaciente) {
        this.idpaciente = idpaciente;
    }
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }
    public Integer getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(Integer nrodoc) {
        this.nrodoc = nrodoc;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


