package pacientes.entity;
// Generated 30-nov-2018 19:32:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer idpaciente;
     private String nombre;
     private String apellido;
     private String tipodoc;
     private Integer nrodoc;
     private Integer telefono;
     private String email;
     private Set domicilios = new HashSet(0);

    public Paciente() {
    }

    public Paciente(String nombre, String apellido, String tipodoc, Integer nrodoc, Integer telefono, String email, Set domicilios) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipodoc = tipodoc;
       this.nrodoc = nrodoc;
       this.telefono = telefono;
       this.email = email;
       this.domicilios = domicilios;
    }
   
    public Integer getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(Integer idpaciente) {
        this.idpaciente = idpaciente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }
    public Integer getNrodoc() {
        return this.nrodoc;
    }
    
    public void setNrodoc(Integer nrodoc) {
        this.nrodoc = nrodoc;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set domicilios) {
        this.domicilios = domicilios;
    }






}


